image: docker:19
stages:
  - build

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_jsi:
  stage: build
  script:
    - export TARGET=jsi
    - export IMAGE_NAME_LATEST=$CI_REGISTRY_IMAGE/$TARGET:latest
    - export IMAGE_NAME_REF=$CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_REF_NAME
    - docker build --pull --tag $IMAGE_NAME_LATEST --tag $IMAGE_NAME_REF ./$TARGET
    - docker push $IMAGE_NAME_LATEST && docker push $IMAGE_NAME_REF

build_simple-api:
  stage: build
  script:
    - export TARGET=simple-api
    - export IMAGE_NAME_LATEST=$CI_REGISTRY_IMAGE/$TARGET:latest
    - export IMAGE_NAME_REF=$CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_REF_NAME
    - docker build --pull --tag $IMAGE_NAME_LATEST --tag $IMAGE_NAME_REF ./$TARGET
    - docker push $IMAGE_NAME_LATEST && docker push $IMAGE_NAME_REF

build_loc-by-postcode:
  stage: build
  script:
    - export TARGET=loc-by-postcode
    - export IMAGE_NAME_LATEST=$CI_REGISTRY_IMAGE/$TARGET:latest
    - export IMAGE_NAME_REF=$CI_REGISTRY_IMAGE/$TARGET:$CI_COMMIT_REF_NAME
    - docker build --pull --tag $IMAGE_NAME_LATEST --tag $IMAGE_NAME_REF ./$TARGET
    - docker push $IMAGE_NAME_LATEST && docker push $IMAGE_NAME_REF
