name: Build Docker Images
on: [push]

jobs:
  build:
    name: Build & push docker images
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message,'[skip ci]')"
    defaults:
      run:
        shell: bash
    steps:
    - name: Get repository path
      id: repository_path
      run: |
        echo ::set-output name=info::${GITHUB_REPOSITORY}
        echo ${GITHUB_REPOSITORY}
    - uses: actions/checkout@v1
    - name: Build & Push jsi
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ steps.repository_path.outputs.info }}/jsi
        path: ./jsi
        tag_with_ref: true
        always_pull: true
        push: true
    - name: Build & Push simple-api
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ steps.repository_path.outputs.info }}/simple-api
        path: ./simple-api
        tag_with_ref: true
        always_pull: true
        push: true
    - name: Build & Push loc-by-postcode
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ steps.repository_path.outputs.info }}/loc-by-postcode
        path: ./simple-api
        tag_with_ref: true
        always_pull: true
        push: true
