name: Build Docker Images
on: [push]

jobs:
  build:
    name: Build & push docker images
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push jsi
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ env.GITHUB_REPOSITORY }}/jsi
        path: ./jsi
        tag_with_ref: true
        always_pull: true
        push: true
    - name: Build & Push simple-api
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ env.GITHUB_REPOSITORY }}/simple-api
        path: ./simple-api
        tag_with_ref: true
        always_pull: true
        push: true

